export default {
  async fetch(request) {
    const files = {
      "/": `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ResumeCraft AI</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="header">
    <h1>ResumeCraft AI</h1>
    <p class="tagline">Crafting Your Future, One Resume at a Time</p>
  </header>
  <main class="container">
    <h2>MVP Plan</h2>
    <pre>✅ You&#39;re ready to deploy your MVP!</pre>
  </main>
  <footer class="footer">
    <p>Generated by AI on 8/4/2025</p>
  </footer>
  <script src="app.js"></script>
</body>
</html>`,
      "/index.html": `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ResumeCraft AI</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="header">
    <h1>ResumeCraft AI</h1>
    <p class="tagline">Crafting Your Future, One Resume at a Time</p>
  </header>
  <main class="container">
    <h2>MVP Plan</h2>
    <pre>✅ You&#39;re ready to deploy your MVP!</pre>
  </main>
  <footer class="footer">
    <p>Generated by AI on 8/4/2025</p>
  </footer>
  <script src="app.js"></script>
</body>
</html>`,
      "/styles.css": `body {
  font-family: sans-serif;
  background: #f5f5f5;
  color: #333;
  margin: 0;
  padding: 0;
  line-height: 1.6;
}
.header {
  background: #0066cc;
  color: #fff;
  padding: 1rem;
  text-align: center;
}
.container {
  max-width: 800px;
  margin: 2rem auto;
  padding: 0 1rem;
}
.footer {
  text-align: center;
  padding: 1rem;
  font-size: 0.8rem;
  color: #666;
}`,
      "/app.js": `export function init() {
  console.log("App initialized");
}
window.addEventListener("DOMContentLoaded", init);`
    };

    const url = new URL(request.url);
    const path = url.pathname in files ? url.pathname : "/index.html";
    const content = files[path];
    const contentType = getContentType(path);

    return new Response(content, {
      headers: { "Content-Type": contentType }
    });
  }
};

function getContentType(path) {
  if (path.endsWith(".html")) return "text/html; charset=utf-8";
  if (path.endsWith(".css")) return "text/css";
  if (path.endsWith(".js")) return "application/javascript";
  return "text/plain";
}
